### PR TITLE
chore: manual content migration

### PR DESCRIPTION
**Pull request by PauloASilva**
I reached out Project Leader offering help to migrate the project page without success.

Since I lead the [OWASP Go Secure Coding Practices][1] which is based on this project, I would like to contribute with a proper content migration.

Cheers,
Paulo A. Silva

[1]: https://www2.owasp.org/www-project-go-secure-coding-practices-guide/

### CODE REVIEW

**Comment by jgadsden** [comment]
I also would like @PauloASilva pull request to be merged into main (it would be good to rename the 'master' branch as 'main')
@hblankenship are you able to give write permissions?
The company I work for would like to use OWASP secure coding practices but can not do this until it is properly maintained - the PDF for this project is November 2010, so a lot of work needs to be done.

I am a leader of another OWASP project (Threat Dragon) so I can help out here if you need me to

**Comment by hblankenship** [comment]
@PauloASilva , @jgadsden Are either of you offering to lead this project?

**Comment by jgadsden** [comment]
Yes, I am happy to help take this on and be one of the leaders. It would be good to have an up-to-date OWASP secure coding practices
Wondering why has nobody done anything on this for 12 years or so ... maybe get the project on its feet and see if there is an appetite for it? The Go-SCP is very popular (all credit to @PauloASilva )

**Comment by jgadsden** [comment]
Hello @hblankenship , I have contacted Keith Turpin and we can see what he comes back with. I am happy to get this project going again if you want to go ahead and provide me with access to this repo

**Comment by PauloASilva** [comment]
> @PauloASilva , @jgadsden Are either of you offering to lead this project?

That was not exactly my original intent when opening this PR.
I like this project and believe it still makes sense: I've contributed to it in the past (v1.3 translation) and built the [OWASP Go Secure Coding Practices][1] around it.

I am already co-leading two OWASP Projects: [Go Secure Coding Practices][1] and the [API Security Project][2], what represents a considerable effort. I'm not sure whether I can give the OWASP SCP Project the required attention it  needs/deserves: I think I prefer to remain a regular volunteer/contributor.

Cheers,
Paulo A. Silva

[1]: https://owasp.org/www-project-go-secure-coding-practices-guide/
[2]: https://owasp.org/www-project-api-security/

**Comment by jgadsden** [comment]
Understood @PauloASilva , I appreciate the amount of effort leading an OWASP project ... let alone 3 if you took this one on as well.
@hblankenship I am happy to get this project going again. Could you give me access please?
I am already a leader of an OWASP project, Threat Dragon, so I should be a safe pair of hands

**Comment by hblankenship** [comment]
@jgadsden Done and I'll let you handle this PR

**Comment by jgadsden** [comment]
Thanks @hblankenship I am now in and have admin access
@PauloASilva I will review and merge the PR this evening +1

**Review by jgadsden — APPROVED** [review]
Looks great, thanks @PauloASilva 
I suggest we go ahead and merge, which will give us the base from which to make further changes
Do you want the honour of merge? I have given you the authorizations

**Comment by PauloASilva** [comment]
> Do you want the honour of merge? I have given you the authorizations

Yeah, sure, but it still says "_Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests._".

Would you mind to double check the repository permissions: assigning the PR to me is not enough.

Cheers,
Paulo A. Silva

**Comment by PauloASilva** [comment]
> Do you want the honour of merge? I have given you the authorizations

Yeah, sure, but it still says "_Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests._".

Would you mind to double check the repository permissions: assigning the PR to me is not enough.

Cheers,
Paulo A. Silva

**Comment by PauloASilva** [comment]
> Do you want the honour of merge? I have given you the authorizations

Yeah, sure, but it still says "_Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests._".

Would you mind to double check the repository permissions: assigning the PR to me is not enough.

Cheers,
Paulo A. Silva

**Pull request merged**
